[package]
name = "manytris_bot_vulkan"
version = "0.1.0"
edition = "2021"

[dependencies]
manytris_bot = {path = "../manytris_bot"}
manytris_core = {path = "../manytris_core"}

vulkano = {workspace = true}
vulkano-shaders = {workspace = true}
