[workspace]
members = [ "manytris_bevy", "manytris_bot","manytris_core"]

[workspace.dependencies]
bevy = "0.13.1"
enum-iterator = "2.0.0"
ewebsock = "0.5.0"
rand = "0.8.5"
tungstenite = "0.21.0"
serde = { version = "1.0.197", features = ["derive"] }
rmp-serde = "1.2.0"
url = "2.5.0"
clap = { version = "4.5.7", features = ["derive"] }
ordered-float = "4.2.2"
enum-map = "2.7.3"
uuid = { version = "1.10.0", features = ["js", "v4"] }

# Mac-specific dependencies
metal = "0.29.0"
genetic_algorithm = "0.8.2"


[package]
name = "manytris"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
manytris_bevy = {path = "manytris_bevy"}
clap = {workspace = true}

[target.'cfg(target_os = "macos")'.dependencies]
manytris_bevy = {path = "manytris_bevy", features=["bot"]}
