[package]
name = "manytris"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.13.1"
enum-iterator = "2.0.0"
ewebsock = "0.5.0"
rand = "0.8.5"
tungstenite = "0.21.0"
serde = { version = "1.0.197", features = ["derive"] }
rmp-serde = "1.2.0"
url = "2.5.0"
clap = { version = "4.5.7", features = ["derive"] }
genetic_algorithm = "0.8.2"
ordered-float = "4.2.2"
