apiVersion: v1
kind: Pod
metadata:
  name: manytris-manager-server
spec:
  containers:
  - name: server
    image: leighpauls/manytris-manager:dev
    ports:
    - name: manager-port
      containerPort: 3000
      hostPort: 3000
      protocol: TCP
      hostIP: 0.0.0.0
