apiVersion: v1
kind: Pod
metadata:
  name: manytris-manager-server
spec:
  containers:
  - name: server
    image: leighpauls/manytris-manager:dev
    ports:
    - name: manager-port
      containerPort: 3000
      hostPort: 3000
      protocol: TCP
      hostIP: 0.0.0.0

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: game-manager
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - nodes
  verbs:
  - get
  - list
  - delete
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: game-manager-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: game-manager
subjects:
- kind: ServiceAccount
  name: default
  namespace: manytris
