FROM rust:1.82-slim-bullseye AS builder

# Set environment variables for Rust
ENV RUST_BACKTRACE=1

# Install required system dependencies
RUN apt-get update && apt-get install -y \
    g++ \
    libx11-dev \
    libxi-dev \
    libxrandr-dev \
    libxcursor-dev \
    libvulkan-dev \
    libudev-dev \
    pkg-config \
    libasound2-dev \
    libxkbcommon-x11-0 \
    libxkbcommon-dev \
    cmake \
    git \
    python3
