[package]
name = "manytris_core"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = {workspace = true}
enum-iterator = {workspace = true}
enum-map = {workspace = true}
rand = {workspace = true}
serde = {workspace = true}
