[package]
name = "manytris_game_manager"
version = "0.1.0"
edition = "2021"

[dependencies]
kube = "0.97.0"
k8s-openapi = { version = "0.23.0", features = ["latest"] }
tokio = {workspace = true}
anyhow = "1.0.93"
