[package]
name = "manytris_bot"
version = "0.1.0"
edition = "2021"

[dependencies]
manytris_core = {path = "../manytris_core"}

anyhow = {workspace = true}
bytemuck = {workspace = true}
enum-iterator = {workspace = true}
enum-map = {workspace = true}
ordered-float = {workspace = true}

